displayName=Clan Kick Protector
author=Absent
description=When turned on, removes the 'Kick' option from the Friends Chat menu.
tags=clan, antikick
version=1.0
plugins=com.clankickprotector.ClanKickProtectorPlugin
build=standard
